package no.nav.syfo.controller.domain.sykepengesoknad.oppsumering

enum class Sporsmalstype {
    ANSVAR_BEKREFTET, EGENMELDINGSDAGER, GJENOPPTATT_ARBEID_FULLT_UT, FERIE_PERMISJON_UTENLANDSOPPHOLD, AKTIVITET, INNTEKTSKILDER, UTDANNING, ARBEIDSGIVER_FORSKUTTERER
}
