apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiasyforest
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /modiasyforest/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /modiasyforest/internal/isReady
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /modiasyforest/internal/prometheus
  ingresses:
    - "https://modiasyforest.dev.intern.nav.no"
    - "https://modiasyforest.dev-fss-pub.nais.io"
    - "https://modiasyforest.nais.preprod.local"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://modiasyforest.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/azuread/data/dev/creds/modiasyforest"
        mountPath: "/secrets/azuread/modiasyforest"
      - kvPath: "/serviceuser/data/dev/srvmodiasyforest"
        mountPath: "/secrets/serviceuser/modiasyforest"
      - kvPath: "/kv/preprod/fss/modiasyforest/default"
        mountPath: "/secrets/vault"
  env:
    - name: APP_NAME
      value: "modiasyforest"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_DISCOVERYURL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_ACCEPTEDAUDIENCE
      value: 38e07d31-659d-4595-939a-f18dce3446c5,33ad42cc-b88c-45c9-b640-8c8a4c93d3a1
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: DKIF_URL
      value: "https://dkif.nais.preprod.local"
    - name: EREG_BASEURL
      value: https://modapp-q1.adeo.no
    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: "https://security-token-service.nais.preprod.local"
    - name: SYFONARMESTELEDER_URL
      value: "https://syfonarmesteleder.nais.preprod.local"
    - name: SYFOSYKETILFELLE_URL
      value: "https://syfosyketilfelle.nais.preprod.local"
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local/syfo-tilgangskontroll/api/tilgang
    - name: AD_ACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: SYFONARMESTELEDER_ID
      value: a7e7ad0e-4e17-4f19-8aa6-39d73e62fff8
