apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiasyforest
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /modiasyforest/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /modiasyforest/internal/isReady
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /modiasyforest/internal/prometheus
  ingresses:
    - "https://modiasyforest.dev.intern.nav.no"
    - "https://modiasyforest.dev-fss-pub.nais.io"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://modiasyforest.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/serviceuser/data/dev/srvmodiasyforest"
        mountPath: "/secrets/serviceuser/modiasyforest"
      - kvPath: "/kv/preprod/fss/modiasyforest/default"
        mountPath: "/secrets/vault"
  env:
    - name: APP_NAME
      value: "modiasyforest"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: DKIF_URL
      value: "https://dkif.nais.preprod.local"
    - name: EREG_BASEURL
      value: https://modapp-q1.adeo.no
    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql
    - name: NARMESTELEDER_URL
      value: "https://narmesteleder.dev.nav.no"
    - name: NARMESTELEDER_CLIENT_ID
      value: "faaa3c37-a241-4d04-a0fa-92ceff7c1c94"
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: "https://security-token-service.nais.preprod.local"
    - name: SYFOSYKETILFELLE_URL
      value: "https://syfosyketilfelle.nais.preprod.local"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local/syfo-tilgangskontroll/api/tilgang
