no.nav.security.oidc:
  issuers: veileder
  issuer:
    veileder:
      discoveryurl: <syfonais>
      accepted_audience: <syfonais>
      cookie_name: isso-idtoken

logging.config: classpath:logback-spring.xml

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

server:
  servlet:
    context-path: /modiasyforest

spring:
  main.banner-mode: 'off'
  jta.atomikos.datasource:
    max-pool-size: 32
    min-pool-size: 8
  cache.type: redis
  redis:
    host: modiasyforest-redis
    port: 6379

dev: false
