package no.nav.syfo.controller.domain.sykepengesoknad;

public enum AnnenInntektskildeType {
    ANDRE_ARBEIDSFORHOLD, SELVSTENDIG_NAERINGSDRIVENDE, SELVSTENDIG_NAERINGSDRIVENDE_DAGMAMMA, JORDBRUKER_FISKER_REINDRIFTSUTOEVER, FRILANSER, ANNET
}
