package no.nav.syfo.controller.domain.sykepengesoknad

enum class AnnenInntektskildeType {
    ANDRE_ARBEIDSFORHOLD, SELVSTENDIG_NAERINGSDRIVENDE, SELVSTENDIG_NAERINGSDRIVENDE_DAGMAMMA, JORDBRUKER_FISKER_REINDRIFTSUTOEVER, FRILANSER, ANNET
}
